Repository toylet/toylet, pull requests merged in 2019-06, with the labels that each got.

#2 setup server package
  server/.gitignore
  server/package.json
Labels: enhancement

#10 Feature/back/signup skeleton
  client/README.md
  server/app.js
  server/config/config.json
  server/lib/signup.js
  server/package.json
  server/router/index.js
  server/router/v1/signup.js
  server/yarn.lock
Labels: enhancement

#15 Feature/front/login router
  client/package.json
  client/src/App.tsx
  client/src/components/Login.tsx
  client/src/components/Main.tsx
  client/src/react-app-env.d.ts
  client/yarn.lock
Labels: enhancement, front-end

#16 Feature/back/signup
  server/lib/signup.js
  server/model/user_schema.js
  server/router/v1/signup.js
Labels: back-end, enhancement

#23 add signup
  server/models/user_model.js
  server/router/v1/signup.js
Labels: back-end, enhancement

#24 revise signup
  server/app.js
  server/router/index.js
  server/router/v1/signin.js
  server/router/v1/signup.js
Labels: back-end, enhancement

#26 implement signin
  server/router/v1/signin.js
Labels: back-end, enhancement

#28 create project schema
  server/models/project.js
  server/models/user.js
  server/router/v1/makeProject.js
  server/router/v1/signin.js
  server/router/v1/signup.js
Labels: back-end, enhancement

#30 create-UserProjectMapsSchema
  server/models/user.js
  server/models/userProjectMaps.js
  server/router/v1/signup.js
Labels: back-end, enhancement

#32 add-project-query
  server/models/project.js
  server/router/index.js
  server/router/v1/makeProject.js
  server/router/v1/project.js
Labels: back-end, enhancement

#34 modift user API
  server/models/project.js
  server/router/index.js
  server/router/v1/signin.js
  server/router/v1/user.js
Labels: back-end, enhancement

#36 modify-user-URI
  server/router/v1/user.js
Labels: back-end, enhancement

#38 add_project_CRUD
  server/router/v1/project.js
  server/router/v1/user.js
Labels: back-end, enhancement

#40 modify project crud
  server/app.js
  server/models/project.js
  server/router/v1/project.js
Labels: back-end, enhancement

#43 Feature/front/post list and editor
  client/package.json
  client/public/index.html
  client/src/App.module.scss
  client/src/App.tsx
  client/src/components/Main.tsx
  client/src/components/NewPost.module.scss
  client/src/components/NewPost.tsx
  client/src/components/ProjectDetail.tsx
  client/src/components/ProjectList.module.scss
  client/src/components/ProjectList.tsx
  client/src/index.scss
  client/src/react-app-env.d.ts
  client/src/svgs/download.svg
  client/src/svgs/github.svg
  client/src/svgs/tip.svg
  client/yarn.lock
Labels: enhancement

#44 add map crud
  server/models/project.js
  server/models/user.js
  server/router/index.js
  server/router/v1/map.js
  server/router/v1/project.js
Labels: back-end, enhancement

#45 add-github-commit-viewer
  server/models/userProjectMaps.js
  server/router/index.js
  server/router/v1/gitloader.js
Labels: back-end, enhancement

#49 uploadImage
  server/router/v1/upload.js
Labels: back-end, enhancement

#51 addGit
  server/models/user.js
  server/router/index.js
  server/router/v1/gitloader.js
Labels: back-end, enhancement

#53 revise-apis
  server/models/project.js
  server/models/user.js
  server/router/v1/gitloader.js
  server/router/v1/project.js
  server/router/v1/user.js
Labels: back-end, enhancement

#55 modifyModel
  server/models/project.js
  server/models/userProjectMaps.js
  server/router/v1/project.js
  server/router/v1/user.js
Labels: back-end, enhancement

#57 Feature/back/gitloader
  server/models/user.js
  server/router/v1/gitloader.js
  server/router/v1/project.js
Labels: back-end, enhancement

#58 hotfix
  server/router/v1/project.js
Labels: back-end, bug

#56 Add MyProjects, DiscoverProjects Page
  client/src/App.tsx
  client/src/components/Discover.tsx
  client/src/components/Discover/Discover.module.scss
  client/src/components/Discover/index.tsx
  client/src/components/MyProjects/MyProjects.module.scss
  client/src/components/MyProjects/index.tsx
  client/src/components/ProjectList.module.scss
  client/src/components/ProjectList.tsx
  client/src/components/common/ProjectCard/ProjectCard.module.scss
  client/src/components/common/ProjectCard/index.tsx
  client/src/components/common/SideLayout/SideLayout.module.scss
  client/src/components/common/SideLayout/index.tsx
  client/src/components/common/Sidebar/Sidebar.module.scss
  client/src/components/common/Sidebar/index.tsx
  client/src/index.css
  client/src/index.scss
  client/src/index.tsx
  client/src/styles/_colors.scss
  client/src/styles/_mixins.scss
  client/src/svgs/icon-discover.svg
  client/src/svgs/icon-hallofbest.svg
  client/src/svgs/icon-myprojects.svg
  client/src/svgs/icon-none.svg
  client/src/svgs/icon-should-write.svg
  client/src/svgs/icon-wrote.svg
Labels: front-end

#61 updateMapSchema
  server/models/userProjectMaps.js
  server/router/v1/map.js
Labels: back-end, enhancement

#64 modifyUserSchema
  server/models/user.js
  server/router/v1/user.js
Labels: back-end, enhancement

#66 modifyProjectSchema
  server/models/project.js
  server/router/v1/project.js
Labels: back-end, enhancement

#67 modifyProjectSchemaLittleBit
  server/router/v1/project.js
Labels: back-end, enhancement
